export const CODEX_ADAPTER_ERROR_CODES = Object.freeze({
  AUTH_REQUIRED: "CODEX_AUTH_REQUIRED",
  BUSY: "CODEX_ADAPTER_BUSY",
  CLOSED: "CODEX_ADAPTER_CLOSED",
  CONFIG_ISOLATION_UNSUPPORTED: "CODEX_CONFIG_ISOLATION_UNSUPPORTED",
  EXECUTABLE_NOT_FOUND: "CODEX_EXECUTABLE_NOT_FOUND",
  EXECUTABLE_UNTRUSTED: "CODEX_EXECUTABLE_UNTRUSTED",
  MCP_NOT_READY: "CODEX_MCP_NOT_READY",
  MODEL_UNAVAILABLE: "CODEX_MODEL_UNAVAILABLE",
  PROCESS_EXITED: "CODEX_PROCESS_EXITED",
  PROTOCOL: "CODEX_APP_SERVER_PROTOCOL_ERROR",
  SCHEMA_INCOMPATIBLE: "CODEX_APP_SERVER_SCHEMA_INCOMPATIBLE",
  REQUEST_FAILED: "CODEX_APP_SERVER_REQUEST_FAILED",
  REQUEST_TIMEOUT: "CODEX_APP_SERVER_REQUEST_TIMEOUT",
  THREAD_CLEANUP_INCOMPLETE: "CODEX_THREAD_CLEANUP_INCOMPLETE",
  UNSUPPORTED_VERSION: "CODEX_UNSUPPORTED_VERSION",
  WORKSPACE_WRITE_REQUIRED: "CODEX_WORKSPACE_WRITE_REQUIRED",
} as const);

export type CodexAdapterErrorCode =
  (typeof CODEX_ADAPTER_ERROR_CODES)[keyof typeof CODEX_ADAPTER_ERROR_CODES];

export class CodexAdapterError extends Error {
  readonly code: CodexAdapterErrorCode;

  constructor(code: CodexAdapterErrorCode, cause?: unknown) {
    super(code, cause === undefined ? undefined : { cause });
    this.name = "CodexAdapterError";
    this.code = code;
  }
}
