export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_TOKEN: "INVALID_TOKEN",
  ORIGIN_NOT_ALLOWED: "ORIGIN_NOT_ALLOWED",
  SOURCE_NOT_FOUND: "SOURCE_NOT_FOUND",
  SOURCE_OUTSIDE_ROOT: "SOURCE_OUTSIDE_ROOT",
  SOURCE_TOO_LARGE: "SOURCE_TOO_LARGE",
  EDITOR_OPEN_FAILED: "EDITOR_OPEN_FAILED",
  DATA_FLOW_DISABLED: "DATA_FLOW_DISABLED",
  DATA_FLOW_SOURCE_STALE: "DATA_FLOW_SOURCE_STALE",
  DATA_FLOW_ANALYSIS_CANCELLED: "DATA_FLOW_ANALYSIS_CANCELLED",
  AI_DISABLED: "AI_DISABLED",
  PROVIDER_NOT_CONFIGURED: "PROVIDER_NOT_CONFIGURED",
  PROVIDER_AUTH_FAILED: "PROVIDER_AUTH_FAILED",
  PROVIDER_PROTOCOL_UNSUPPORTED: "PROVIDER_PROTOCOL_UNSUPPORTED",
  MODEL_NOT_ALLOWED: "MODEL_NOT_ALLOWED",
  MODEL_TOOL_CALL_UNSUPPORTED: "MODEL_TOOL_CALL_UNSUPPORTED",
  PROVIDER_RATE_LIMITED: "PROVIDER_RATE_LIMITED",
  AGENT_BUSY: "AGENT_BUSY",
  AGENT_LIMIT_EXCEEDED: "AGENT_LIMIT_EXCEEDED",
  AGENT_CANCELLED: "AGENT_CANCELLED",
  EXTERNAL_HANDOFF_DISABLED: "EXTERNAL_HANDOFF_DISABLED",
  EXTERNAL_HANDOFF_UNAVAILABLE: "EXTERNAL_HANDOFF_UNAVAILABLE",
  HANDOFF_VALIDATION_FAILED: "HANDOFF_VALIDATION_FAILED",
  HANDOFF_SOURCE_STALE: "HANDOFF_SOURCE_STALE",
  HANDOFF_NOT_FOUND: "HANDOFF_NOT_FOUND",
  HANDOFF_EXPIRED: "HANDOFF_EXPIRED",
  HANDOFF_CURSOR_INVALID: "HANDOFF_CURSOR_INVALID",
  HANDOFF_RESPONSE_TOO_LARGE: "HANDOFF_RESPONSE_TOO_LARGE",
  BRIDGE_UNAUTHORIZED: "BRIDGE_UNAUTHORIZED",
  BRIDGE_PROTOCOL_MISMATCH: "BRIDGE_PROTOCOL_MISMATCH",
  BRIDGE_BUSY: "BRIDGE_BUSY",
  EXTERNAL_AGENT_BUSY: "EXTERNAL_AGENT_BUSY",
  ACTIVE_ADAPTER_CONFLICT: "ACTIVE_ADAPTER_CONFLICT",
  ACTIVE_ADAPTER_LEASE_INVALID: "ACTIVE_ADAPTER_LEASE_INVALID",
  ACTIVE_DISPATCH_INVALID: "ACTIVE_DISPATCH_INVALID",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_AMBIGUOUS: "SESSION_AMBIGUOUS",
  SESSION_CLOSED: "SESSION_CLOSED",
  WORKTREE_DIRTY: "WORKTREE_DIRTY",
  WORKTREE_NOT_REPOSITORY: "WORKTREE_NOT_REPOSITORY",
  WORKTREE_OPERATION_IN_PROGRESS: "WORKTREE_OPERATION_IN_PROGRESS",
  WORKTREE_CONFLICTED: "WORKTREE_CONFLICTED",
  WORKTREE_LOCAL_CHANGES_TOO_LARGE: "WORKTREE_LOCAL_CHANGES_TOO_LARGE",
  WORKTREE_UNTRACKED_UNSUPPORTED: "WORKTREE_UNTRACKED_UNSUPPORTED",
  WORKTREE_LOCAL_CHANGES_UNSUPPORTED: "WORKTREE_LOCAL_CHANGES_UNSUPPORTED",
  TOOL_DENIED: "TOOL_DENIED",
  TOOL_INPUT_INVALID: "TOOL_INPUT_INVALID",
  TOOL_ARGUMENTS_INVALID: "TOOL_ARGUMENTS_INVALID",
  TOOL_CALL_ID_CONFLICT: "TOOL_CALL_ID_CONFLICT",
  TOOL_PATH_DENIED: "TOOL_PATH_DENIED",
  PATCH_REJECTED: "PATCH_REJECTED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  APPLY_CONFLICT: "APPLY_CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_CODE_VALUES = Object.freeze(Object.values(ERROR_CODES));

export function isErrorCode(value: unknown): value is ErrorCode {
  return (
    typeof value === "string" &&
    (ERROR_CODE_VALUES as readonly string[]).includes(value)
  );
}
