export { SpotPatchError } from "./errors/spotpatch-error.js";
export {
  ERROR_CODES,
  ERROR_CODE_VALUES,
  CONTEXTUAL_ASK_ERROR_CODES,
  isErrorCode,
  type ContextualAskErrorCode,
  type ErrorCode,
} from "./errors/error-code.js";
export {
  isSensitiveName,
  redactSensitiveText,
  sanitizeUrl,
} from "./security/redaction.js";
export {
  MAX_ANNOTATION_INSTRUCTION_CHARACTERS,
  MAX_ANNOTATION_TARGETS,
  MAX_TARGET_INSTRUCTION_CHARACTERS,
  SPOTPATCH_LOCALE_PREFERENCES,
  SPOTPATCH_LOCALES,
  type ElementContext,
  type PageContext,
  type SpotAnnotation,
  type SpotPatchLocale,
  type SpotPatchLocalePreference,
  type SpotTargetContext,
} from "./model/annotation.js";
export type { CodeContext, ContextBudget } from "./model/code-context.js";
export {
  askAnswerBlockSchema,
  askAnswerDraftBlockSchema,
  askAnswerDraftSchema,
  askAnswerResultSchema,
  askAnswerWarningSchema,
  askDraftCitationSchema,
  askDraftOriginSchema,
  askSourceReferenceSchema,
  contextualAskExecutorCapabilitySchema,
  contextualAskExecutorPreferenceSchema,
  contextualAskOptionsSchema,
  contextualAskCapabilitySchema,
  spotAskTaskEnvelopeSchema,
  spotChangeTaskEnvelopeSchema,
  spotSelectionContextSchema,
  spotSelectionTargetSchema,
  spotTaskEnvelopeSchema,
  type AskAnswerBlock,
  type AskAnswerDraft,
  type AskAnswerDraftBlock,
  type AskAnswerResult,
  type AskAnswerWarning,
  type AskDraftCitation,
  type AskDraftOrigin,
  type AskSourceReference,
  type ContextualAskCapability,
  type ContextualAskExecutorCapability,
  type ContextualAskExecutorPreference,
  type ContextualAskOptions,
  type SpotAskTaskEnvelope,
  type SpotChangeTaskEnvelope,
  type SpotSelectionContext,
  type SpotSelectionTarget,
  type SpotTaskEnvelope,
} from "./model/contextual-ask.js";
export {
  DATA_FLOW_QUERY_ADAPTER_MODULES,
  DATA_FLOW_QUERY_HOOK_NAMES,
  DATA_FLOW_TRPC_CLIENT_FACTORY_NAMES,
  DATA_FLOW_TRPC_PROXY_FACTORY_NAMES,
  DATA_FLOW_TRPC_REQUEST_METHODS,
  DATA_FLOW_TRPC_ROOT_FACTORY_NAMES,
} from "./model/data-flow-adapters.js";
export {
  DATA_FLOW_ASSOCIATION_KINDS,
  DATA_FLOW_DIAGNOSTIC_CODES,
  DATA_FLOW_EXECUTION_STATES,
  DATA_FLOW_FRESHNESS_STATES,
  DATA_FLOW_PROOF_STATES,
  DATA_FLOW_SCHEMA_VERSION,
  DATA_FLOW_URL_QUERY_KEY_LIMIT,
  DEFAULT_DATA_FLOW_LIMITS,
  DEFAULT_RUNTIME_DATA_FLOW_LIMITS,
  dataDependencySchema,
  componentDataFlowReportSchema,
  networkObservationSchema,
  pageDataFlowReportSchema,
  runtimeDataFlowConfigSchema,
  type AnalysisBaseline,
  type AssociationKind,
  type ComponentDataFlowReport,
  type ComponentIdentity,
  type DataDependency,
  type DataFlowCapability,
  type DataFlowCapabilityReason,
  type DataFlowDiagnostic,
  type DataFlowDiagnosticCode,
  type DataFlowLimits,
  type DataParameter,
  type DataResponseDescriptor,
  type EvidenceRef,
  type EvidenceSourceRef,
  type ExecutionState,
  type FreshnessState,
  type NetworkObservation,
  type PageDataFlowReport,
  type ProofState,
  type ReportCompleteness,
  type RequestOrigin,
  type RuntimeDataFlowConfig,
  type RuntimeDataFlowLimits,
  type SanitizedObservedUrl,
} from "./model/data-flow.js";
export {
  limitDataFlowReportCollections,
  type DataFlowCollectionLimitOptions,
} from "./model/data-flow-budget.js";
export {
  runtimeConfigSchema,
  SPOTPATCH_NEXT_BUNDLERS,
  SPOTPATCH_NEXT_ROUTER_KINDS,
  type SpotPatchNextBundler,
  type SpotPatchNextRouterKind,
  type SpotPatchRuntimeConfig,
} from "./model/runtime-config.js";
export {
  SPOTPATCH_EDITOR_PREFERENCES,
  type EditorOpenResult,
  type SpotPatchEditorPreference,
} from "./model/editor.js";
export {
  AGENT_APPLY_MODES,
  AGENT_CAPABILITY_STATES,
  AGENT_CHECK_STATUSES,
  AGENT_FILE_CHANGE_KINDS,
  AGENT_JOB_STATUSES,
  AGENT_WORKSPACE_SNAPSHOT_LIMITS,
  AGENT_WORKSPACE_STATES,
  DEFAULT_AGENT_LIMITS,
  type AgentApplyMode,
  type AgentCapabilitySnapshot,
  type AgentCapabilityState,
  type AgentChangedFile,
  type AgentCheckDefinition,
  type AgentCheckResult,
  type AgentCheckStatus,
  type AgentFileChangeKind,
  type AgentJobResult,
  type AgentJobResultResponse,
  type AgentJobSnapshot,
  type AgentJobStatus,
  type AgentWorkingTreeMode,
  type AgentWorkspaceChangeSummary,
  type AgentWorkspaceHealthSnapshot,
  type AgentWorkspaceState,
  type AgentLimits,
  type AiExecutionOptions,
  type AiModelProfile,
  type AiOptions,
  type AiProviderAuthentication,
  type AiProviderProtocol,
  type OpenAICompatibleProviderOptions,
  type ResolvedAgentCheckDefinition,
  type ResolvedAiExecutionOptions,
  type ResolvedAiModelProfile,
  type ResolvedAiOptions,
  type ResolvedOpenAICompatibleProviderOptions,
  type RuntimeAiConfig,
  type RuntimeAiModelProfile,
  type RuntimeAiProviderProfile,
} from "./model/agent.js";
export type {
  ReactContext,
  SourceConfidence,
  SourceOrigin,
  SourceRef,
} from "./model/source-ref.js";
export type { MatchedStyleRule, StyleContext } from "./model/style-context.js";
export {
  formatSourceMarker,
  parseSourceMarker,
  SOURCE_MARKER_ATTRIBUTE,
  type SourceMarker,
} from "./model/source-marker.js";
export {
  EXTERNAL_AGENT_ACTIONS,
  EXTERNAL_AGENT_AUTH_READINESS,
  EXTERNAL_AGENT_CONNECTION_STATES,
  EXTERNAL_AGENT_CONTROL_LIMITS,
  EXTERNAL_AGENT_CONTROL_SCHEMA_VERSION,
  EXTERNAL_AGENT_DELIVERY_STATUSES,
  EXTERNAL_AGENT_ERROR_CODES,
  EXTERNAL_AGENT_ERROR_RECOVERABILITY,
  EXTERNAL_AGENT_ERROR_STAGES,
  EXTERNAL_AGENT_EXECUTION_STATUSES,
  EXTERNAL_AGENT_GRANT_STATES,
  EXTERNAL_AGENT_MANAGED_ADAPTER_KINDS,
  EXTERNAL_AGENT_MANAGED_PHASES,
  EXTERNAL_AGENT_MANAGED_PROFILE,
  EXTERNAL_AGENT_MODES,
  EXTERNAL_AGENT_VALIDATION_OUTCOMES,
  externalAgentControlCancelRequestSchema,
  externalAgentControlConnectRequestSchema,
  externalAgentControlDisconnectRequestSchema,
  externalAgentControlStatusRequestSchema,
  externalAgentControlStatusSchema,
  externalAgentErrorSchema,
  externalAgentEventSchema,
  externalAgentEventsRequestSchema,
  externalAgentManagedResultSchema,
  externalAgentResultRequestSchema,
  managedCheckSummarySchema,
  managedFileSummarySchema,
  managedTaskStatusSchema,
  managedTimingSummarySchema,
  type ExternalAgentAction,
  type ExternalAgentConnectionState,
  type ExternalAgentControlCancelRequest,
  type ExternalAgentControlConnectRequest,
  type ExternalAgentControlDisconnectRequest,
  type ExternalAgentControlStatus,
  type ExternalAgentErrorCode,
  type ExternalAgentEvent,
  type ExternalAgentEventsRequest,
  type ExternalAgentManagedResult,
  type ExternalAgentResultRequest,
} from "./protocol/external-agent-control.js";
export {
  EXTERNAL_HANDOFF_ACTIVE_ADAPTER_KINDS,
  EXTERNAL_HANDOFF_ACTIVE_ADAPTER_STATES,
  EXTERNAL_HANDOFF_BROKER_PROTOCOL_VERSION,
  EXTERNAL_HANDOFF_DISPATCH_PHASES,
  EXTERNAL_HANDOFF_FRAMEWORKS,
  EXTERNAL_HANDOFF_LIMITS,
  EXTERNAL_HANDOFF_REPORTABLE_DISPATCH_PHASES,
  EXTERNAL_HANDOFF_SNAPSHOT_SCHEMA_VERSION,
  EXTERNAL_HANDOFF_STATES,
  activeAdapterSummarySchema,
  dispatchSummarySchema,
  externalHandoffCapabilityRequestSchema,
  externalHandoffCapabilitySchema,
  externalHandoffPublishDeliverySchema,
  externalHandoffPublishRequestSchema,
  externalHandoffPublishResultSchema,
  externalHandoffReportableDispatchPhaseSchema,
  externalHandoffResolveDeliveryRequestSchema,
  externalHandoffSnapshotSchema,
  externalHandoffStatusRequestSchema,
  externalHandoffStatusResultSchema,
  externalHandoffSummarySchema,
  type ActiveAdapterSummary,
  type DispatchSummary,
  type ExternalHandoffActiveAdapterKind,
  type ExternalHandoffActiveAdapterState,
  type ExternalHandoffCapability,
  type ExternalHandoffDispatchPhase,
  type ExternalHandoffFramework,
  type ExternalHandoffPublishDelivery,
  type ExternalHandoffPublishRequest,
  type ExternalHandoffPublishResult,
  type ExternalHandoffReportableDispatchPhase,
  type ExternalHandoffResolveDeliveryRequest,
  type ExternalHandoffSnapshot,
  type ExternalHandoffState,
  type ExternalHandoffStatusRequest,
  type ExternalHandoffStatusResult,
  type ExternalHandoffSummary,
} from "./protocol/external-handoff.js";
export {
  getAgentJobEndpoint,
  getAskJobEndpoint,
  SPOTPATCH_API_BASE,
  SPOTPATCH_ENDPOINTS,
  SPOTPATCH_TOKEN_HEADER,
  type AgentJobAction,
  type AskJobAction,
} from "./protocol/endpoints.js";
export {
  ASK_ANSWER_WARNING_CODES,
  ASK_EXECUTOR_ANSWER_WARNING_CODES,
  ASK_FILE_COUNT_BUCKETS,
  ASK_JOB_STATUSES,
  ASK_READ_ACTIVITY_STATES,
  ASK_SOURCE_CONFIDENCES,
  CONTEXTUAL_ASK_EXECUTOR_KINDS,
  CONTEXTUAL_ASK_EXECUTOR_STATES,
  CONTEXTUAL_ASK_LIMITS,
  CONTEXTUAL_ASK_PERMISSION_PROFILE,
  CONTEXTUAL_ASK_SCHEMA_VERSION,
  type AskAnswerWarningCode,
  type AskExecutorAnswerWarningCode,
  type AskFileCountBucket,
  type AskJobStatus,
  type AskReadActivityState,
  type AskSourceConfidence,
  type ContextualAskExecutorKind,
  type ContextualAskExecutorState,
} from "./protocol/contextual-ask-constants.js";
export {
  askJobActionRequestSchema,
  askJobCreateRequestSchema,
  askJobEventSchema,
  askJobEventsRequestSchema,
  askJobResultResponseSchema,
  askJobSnapshotSchema,
  contextualAskCapabilityRequestSchema,
  type AskJobActionRequest,
  type AskJobCreateRequest,
  type AskJobEvent,
  type AskJobEventsRequest,
  type AskJobResultResponse,
  type AskJobSnapshot,
  type ContextualAskCapabilityRequest,
} from "./protocol/contextual-ask.js";
export {
  agentCapabilityRequestSchema,
  agentWorkspaceHealthRequestSchema,
  agentJobActionRequestSchema,
  agentJobCreateRequestSchema,
  dataFlowComponentReportRequestSchema,
  dataFlowPageReportRequestSchema,
  openEditorRequestSchema,
  runtimeBootstrapRequestSchema,
  sourceContextRequestSchema,
  spotAnnotationRequestSchema,
  spotTargetContextRequestSchema,
  type AgentCapabilityRequest,
  type AgentJobCreateRequest,
  type DataFlowComponentReportRequest,
  type DataFlowPageReportRequest,
  type OpenEditorRequest,
  type RuntimeBootstrapRequest,
  type SourceContextRequest,
} from "./protocol/requests.js";
export type { AgentJobEvent } from "./protocol/agent-events.js";
export {
  agentCapabilitySnapshotSchema,
  agentWorkspaceHealthSnapshotSchema,
  agentChangedFileSchema,
  agentCheckResultSchema,
  agentJobEventSchema,
  agentJobResultResponseSchema,
  agentJobResultSchema,
  agentJobSnapshotSchema,
} from "./protocol/agent-schemas.js";
export type { ApiFailure, ApiResponse, ApiSuccess } from "./protocol/responses.js";
export { SPOTPATCH_REPOSITORY_URL } from "./product.js";
